name: build_ISO
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Set version variables
      - name: Set version variables
        run: |
          echo "DEBIAN_VERSION=12.8.0" >> $GITHUB_ENV

      # Step 2: Determine ISO URL and file name dynamically
      - name: Fetch latest ISO URL
        run: |
          ISO_BASE_URL="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/"
          ISO_FILE=$(curl -s $ISO_BASE_URL | grep -oP 'href="debian-[0-9\.]+-amd64-netinst.iso"' | head -n 1 | cut -d'"' -f2)
          echo "DEBIAN_ISO_NAME=$ISO_FILE" >> $GITHUB_ENV
          echo "DEBIAN_ISO_URL=${ISO_BASE_URL}${ISO_FILE}" >> $GITHUB_ENV
        shell: bash

      # Step 3: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 4: Prepare the environment
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso dpkg-dev curl gnupg syslinux-utils apt-rdepends

      # Step 5: Download the Debian ISO
      - name: Download Debian ISO
        run: |
          wget -q --show-progress ${{ env.DEBIAN_ISO_URL }} -O ${{ env.DEBIAN_ISO_NAME }}
          ls -lh ${{ env.DEBIAN_ISO_NAME }}
          if [ ! -s "${{ env.DEBIAN_ISO_NAME }}" ]; then
            echo "Error: ISO file not downloaded or empty."
            exit 1
          fi

      # Step 6: Build the custom ISO using a script
      - name: Build custom ISO
        run: |
          chmod +x create_ISO.bash
          sudo ./create_ISO.bash ${{ env.DEBIAN_ISO_NAME }} proxmox_custom.iso

      # Step 7: Verify the custom ISO contents
      - name: Verify custom ISO contents
        run: |
          mkdir -p mnt
          sudo mount -o loop proxmox_custom.iso mnt
          echo "ISO contents:"
          ls -lh mnt/pve/
          sudo umount mnt

      # Step 8: Release the custom ISO
      - uses: ncipollo/release-action@v1
        with:
          commit: "main"
          name: "Download ISO"
          tag: "${{ env.DEBIAN_VERSION }}"
          artifacts: "proxmox_custom.iso"
          updateOnlyUnreleased: true
