name: build_ISO
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso dpkg-dev curl gnupg

      - name: Download Debian ISO
        run: |
          wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.7.0-amd64-netinst.iso

      - name: Build local Proxmox repository
        run: |
          # 1) 向 Proxmox 仓库添加 GPG key & repo
          echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" | sudo tee /etc/apt/sources.list.d/pve-install-repo.list
          curl -fsSL https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg | sudo tee /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg > /dev/null

          # 2) 更新缓存
          sudo apt-get update

          # 3) 下载所需包 (示例)
          mkdir pve
          cd pve
          # 你想安装哪些包就下载哪些
          sudo apt-get download proxmox-ve postfix open-iscsi
          # 还可以下载 chrony / ifupdown2 / 等

          # 4) 生成 Packages 索引
          dpkg-scanpackages . > Packages
          gzip -9c Packages > Packages.gz
          cd ..

      - name: Build custom ISO
        run: |
          sudo bash create_ISO.bash

      - name: Release custom ISO
        uses: ncipollo/release-action@v1
        with:
          commit: "main"
          name: "Download ISO"
          tag: "12.7.0"
          artifacts: "proxmox_custom.iso"
